[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production]
# Production environment variables will be set in Railway dashboard

[environments.production.variables]
NODE_ENV = "production"
